---
title: "Laboratorio #3"
output: html_notebook
---

#### Alan Hurtarte - 19000590

---

# Bias-Variance Tradeoff
```{r}
library(MASS)
library(ISLR)
library(dplyr)
library(ggplot2)

know_data <- Boston %>% 
  dplyr::select(lstat,medv)

names(know_data)[1] <- "input"
names(know_data)[2] <- "output"


know_data.rows <- nrow(know_data)

get_formula <- function(dataset, degree = 2) {
  formula <- paste0("I(","input^",1:degree,")",collapse = '+')
  formula <- paste0("output ~ ",formula)
  return(formula)
}
```

## Ejercicio 1
```{r}

varianza <- function(df, reg, boots, n) {
  # fix randomization seed, make sample() reproducible
  set.seed(527)
  
  sampleSize <- n
  bRows <- df[sample(nrow(df), sampleSize), ]
  # do 7 bootstrap replications
  bSamples <- boots
  
  var_df <- data.frame('VAR' = 1:1)
  
  # loop over bootstraps
  for (b in seq_len(bSamples)) { 
    # make bootstrap draw from bRows
    bData <- bRows[sample(sampleSize, size = sampleSize, replace = TRUE), ]
    # compute your statistic of interest
    y <- lm(formula = reg, data = bData)
    
    y_hat <- predict(y)
    esperanza <- mean(y_hat)
    
    var <- (1 / (n - 1)) * sum((y_hat - esperanza)**2)
    var_df <- rbind(var_df, VAR = c(var))
  }
  var_df = var_df[-1,]
  mean_var <- mean(var_df)
  return(mean_var)
}
var <- varianza(df = know_data, boots = 100, n = know_data.rows, reg = "output ~ input")
print(var)
```

## Ejercicio 2
```{r}
sesgo <- function(df, reg, boots, n) {
  # fix randomization seed, make sample() reproducible
  set.seed(527)
  
  sampleSize <- n
  bRows <- df[sample(nrow(df), sampleSize), ]
  # do 7 bootstrap replications
  bSamples <- boots
  
  sesgo_df <- data.frame('SESGO' = 1:1)
  
  # loop over bootstraps
  for (b in seq_len(bSamples)) { 
    # make bootstrap draw from bRows
    bData <- bRows[sample(sampleSize, size = sampleSize, replace = TRUE), ]
    # compute your statistic of interest
    y <- lm(formula = reg, data = bData)
    
    y_hat <- predict(y)
    esperanza <- mean(y_hat)
    
    bias_square <- (esperanza - y_hat)^2

    sesgo_df <- rbind(sesgo_df, VAR = c(bias_square))
  }
  sesgo_df = sesgo_df[-1,]
  mean_sesgo <- mean(sesgo_df)
  return(mean_sesgo)
}
sesgo(df = know_data, boots = 4, n = 500, reg = "output ~ input")
```

# Ejercicio 3
```{r}

i <- 4
x <- seq(1, i)
results <- data.frame("VAR" = rep(NA, length(x)), "SES" = rep(NA,length(x)))
for (degree in x) {
  var <- varianza(df = know_data, boots = 3, n = know_data.rows, reg = get_formula(know_data, degree = degree))
  ses <- sesgo(df = know_data, boots = 4, n = 500, reg = get_formula(know_data, degree = degree))
  results$VAR[floor(degree)] <- var
  results$SES[floor(degree)] <- ses
}

results

```

```{r}
{plot(x, results$VAR,
main="grapg",
ylab="",
type="l",
col="blue", ylim = c(50, 80));
lines(x,results$SES, col="red");
legend("topleft",
c("Var","ses"),
fill=c("blue","red")
)}
```

# Ejercicio 4

```{r}
head(Boston)
```
```{r}
cor(Boston)
```

```{r}
heatmap(cor(Boston))
```

```{r}
var_ses <- function(df, reg, boots, n) {
  var <- varianza(df = df,reg = reg, boots = boots, n = n)
  ses <- sesgo(df, reg, boots, n)
  sprintf('Var: %f. Ses: %f', var, ses)
}

data <- Boston %>% 
  dplyr::select(lstat,medv,rm,ptratio)

names(data)[1] <- "input"
names(data)[2] <- "output"
names(data)[3] <- "input2"
names(data)[4] <- "input3"

data.rows = nrow(data)
var_ses(df = data,reg = "output ~ input + input2 + input3", boots = 4,n = data.rows)
var_ses(df = data,reg = "output ~ input + input2 ", boots = 4,n = data.rows)
var_ses(df = data,reg = "output ~ input2 + input3 ", boots = 4,n = data.rows)
var_ses(df = data,reg = "output ~ I(input2**2) + I(input3**2) ", boots = 4,n = data.rows)
var_ses(df = data,reg = "output ~ I(input**2) + I(input2**2) + I(input3**2)", boots = 4,n = data.rows)
var_ses(df = data,reg = "output ~ I(input**3) + I(input2**3) + I(input3**3)", boots = 4,n = data.rows)
```

El modelo que parece tener mejor relación entre varianza y sesgo.
'input2 + input3' que sería 'rm + ptratio'

